workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Swagger Petstore - OpenAPI 3.0:
        inputs:
            - location: ./petstore.json
        registry:
            location: registry.speakeasyapi.dev/sheldon-vaughn-test/sandbox/swagger-petstore---open-api-3-0
targets:
    petstore:
        target: typescript
        source: Swagger Petstore - OpenAPI 3.0
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/sheldon-vaughn-test/sandbox/swagger-petstore---open-api-3-0-typescript-code-samples
            blocking: false
