/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Status values that need to be considered for filter
 */
export const Status = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * Status values that need to be considered for filter
 */
export type Status = ClosedEnum<typeof Status>;

export type FindPetsByStatusRequest = {
  /**
   * Status values that need to be considered for filter
   */
  status?: Status | undefined;
};

export type FindPetsByStatusResponse =
  | Uint8Array
  | string
  | Array<components.Pet2>;

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const FindPetsByStatusRequest$inboundSchema: z.ZodType<
  FindPetsByStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: Status$inboundSchema.default("available"),
});

/** @internal */
export type FindPetsByStatusRequest$Outbound = {
  status: string;
};

/** @internal */
export const FindPetsByStatusRequest$outboundSchema: z.ZodType<
  FindPetsByStatusRequest$Outbound,
  z.ZodTypeDef,
  FindPetsByStatusRequest
> = z.object({
  status: Status$outboundSchema.default("available"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByStatusRequest$ {
  /** @deprecated use `FindPetsByStatusRequest$inboundSchema` instead. */
  export const inboundSchema = FindPetsByStatusRequest$inboundSchema;
  /** @deprecated use `FindPetsByStatusRequest$outboundSchema` instead. */
  export const outboundSchema = FindPetsByStatusRequest$outboundSchema;
  /** @deprecated use `FindPetsByStatusRequest$Outbound` instead. */
  export type Outbound = FindPetsByStatusRequest$Outbound;
}

export function findPetsByStatusRequestToJSON(
  findPetsByStatusRequest: FindPetsByStatusRequest,
): string {
  return JSON.stringify(
    FindPetsByStatusRequest$outboundSchema.parse(findPetsByStatusRequest),
  );
}

export function findPetsByStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<FindPetsByStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindPetsByStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindPetsByStatusRequest' from JSON`,
  );
}

/** @internal */
export const FindPetsByStatusResponse$inboundSchema: z.ZodType<
  FindPetsByStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([b64$.zodInbound, z.array(components.Pet2$inboundSchema)]);

/** @internal */
export type FindPetsByStatusResponse$Outbound =
  | Uint8Array
  | Array<components.Pet2$Outbound>;

/** @internal */
export const FindPetsByStatusResponse$outboundSchema: z.ZodType<
  FindPetsByStatusResponse$Outbound,
  z.ZodTypeDef,
  FindPetsByStatusResponse
> = z.union([b64$.zodOutbound, z.array(components.Pet2$outboundSchema)]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FindPetsByStatusResponse$ {
  /** @deprecated use `FindPetsByStatusResponse$inboundSchema` instead. */
  export const inboundSchema = FindPetsByStatusResponse$inboundSchema;
  /** @deprecated use `FindPetsByStatusResponse$outboundSchema` instead. */
  export const outboundSchema = FindPetsByStatusResponse$outboundSchema;
  /** @deprecated use `FindPetsByStatusResponse$Outbound` instead. */
  export type Outbound = FindPetsByStatusResponse$Outbound;
}

export function findPetsByStatusResponseToJSON(
  findPetsByStatusResponse: FindPetsByStatusResponse,
): string {
  return JSON.stringify(
    FindPetsByStatusResponse$outboundSchema.parse(findPetsByStatusResponse),
  );
}

export function findPetsByStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<FindPetsByStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindPetsByStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindPetsByStatusResponse' from JSON`,
  );
}
