/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePetRawResponse =
  | Uint8Array
  | string
  | ReadableStream<Uint8Array>
  | Blob
  | ArrayBuffer
  | Uint8Array;

/** @internal */
export const UpdatePetRawResponse$inboundSchema: z.ZodType<
  UpdatePetRawResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  b64$.zodInbound,
  z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
]);

/** @internal */
export type UpdatePetRawResponse$Outbound =
  | Uint8Array
  | ReadableStream<Uint8Array>
  | Blob
  | ArrayBuffer
  | Uint8Array;

/** @internal */
export const UpdatePetRawResponse$outboundSchema: z.ZodType<
  UpdatePetRawResponse$Outbound,
  z.ZodTypeDef,
  UpdatePetRawResponse
> = z.union([
  b64$.zodOutbound,
  z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetRawResponse$ {
  /** @deprecated use `UpdatePetRawResponse$inboundSchema` instead. */
  export const inboundSchema = UpdatePetRawResponse$inboundSchema;
  /** @deprecated use `UpdatePetRawResponse$outboundSchema` instead. */
  export const outboundSchema = UpdatePetRawResponse$outboundSchema;
  /** @deprecated use `UpdatePetRawResponse$Outbound` instead. */
  export type Outbound = UpdatePetRawResponse$Outbound;
}

export function updatePetRawResponseToJSON(
  updatePetRawResponse: UpdatePetRawResponse,
): string {
  return JSON.stringify(
    UpdatePetRawResponse$outboundSchema.parse(updatePetRawResponse),
  );
}

export function updatePetRawResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetRawResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetRawResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetRawResponse' from JSON`,
  );
}
