/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Category,
  Category$inboundSchema,
  Category$Outbound,
  Category$outboundSchema,
} from "./category.js";
import {
  Tag,
  Tag$inboundSchema,
  Tag$Outbound,
  Tag$outboundSchema,
} from "./tag.js";

/**
 * pet status in the store
 */
export const Status = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * pet status in the store
 */
export type Status = ClosedEnum<typeof Status>;

export type Pet2 = {
  id?: number | undefined;
  name: string;
  category?: Category | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag> | undefined;
  /**
   * pet status in the store
   */
  status?: Status | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z
  .nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> =
  Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
  /** @deprecated use `Status$inboundSchema` instead. */
  export const inboundSchema = Status$inboundSchema;
  /** @deprecated use `Status$outboundSchema` instead. */
  export const outboundSchema = Status$outboundSchema;
}

/** @internal */
export const Pet2$inboundSchema: z.ZodType<Pet2, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int().optional(),
    name: z.string(),
    category: Category$inboundSchema.optional(),
    photoUrls: z.array(z.string()),
    tags: z.array(Tag$inboundSchema).optional(),
    status: Status$inboundSchema.optional(),
  });

/** @internal */
export type Pet2$Outbound = {
  id?: number | undefined;
  name: string;
  category?: Category$Outbound | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag$Outbound> | undefined;
  status?: string | undefined;
};

/** @internal */
export const Pet2$outboundSchema: z.ZodType<Pet2$Outbound, z.ZodTypeDef, Pet2> =
  z.object({
    id: z.number().int().optional(),
    name: z.string(),
    category: Category$outboundSchema.optional(),
    photoUrls: z.array(z.string()),
    tags: z.array(Tag$outboundSchema).optional(),
    status: Status$outboundSchema.optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Pet2$ {
  /** @deprecated use `Pet2$inboundSchema` instead. */
  export const inboundSchema = Pet2$inboundSchema;
  /** @deprecated use `Pet2$outboundSchema` instead. */
  export const outboundSchema = Pet2$outboundSchema;
  /** @deprecated use `Pet2$Outbound` instead. */
  export type Outbound = Pet2$Outbound;
}

export function pet2ToJSON(pet2: Pet2): string {
  return JSON.stringify(Pet2$outboundSchema.parse(pet2));
}

export function pet2FromJSON(
  jsonString: string,
): SafeParseResult<Pet2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pet2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pet2' from JSON`,
  );
}
